CREATE TABLE IF NOT EXISTS "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(255),
  "email" VARCHAR(255) UNIQUE,
  "password" VARCHAR,
  "user_type" VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS "product" (
  "product_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "price" FLOAT
);

CREATE TABLE IF NOT EXISTS "category" (
  "category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS "product_category" (
  "product_id" INTEGER,
  "category_id" INTEGER,
  PRIMARY KEY ("product_id", "category_id")
);

CREATE TABLE IF NOT EXISTS "product_option" (
  "option_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" INTEGER,
  "color" VARCHAR(50),
  "size" VARCHAR(50),
  "stock" INTEGER
);

CREATE TABLE IF NOT EXISTS "cart" (
  "cart_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INTEGER
);

CREATE TABLE IF NOT EXISTS "cart_item" (
  "cart_item_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" INTEGER,
  "product_option_id" INTEGER UNIQUE,
  "amount" INTEGER
);

ALTER TABLE "product_category" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id");

ALTER TABLE "product_category" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("category_id");

ALTER TABLE "product_option" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("product_id");

ALTER TABLE "cart" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "cart_item" ADD FOREIGN KEY ("cart_id") REFERENCES "cart" ("cart_id");

ALTER TABLE "cart_item" ADD FOREIGN KEY ("product_option_id") REFERENCES "product_option" ("option_id");
